
map $http_upgrade $connection_upgrade { default upgrade; '' close; }

server {
    listen 80;
    server_name _;
    root /data/web80;
    charset utf-8;
    index index.html index.htm;
    location / { }
}

server {
    listen 81;
    server_name _;
    root /data/web81;
    charset utf-8;
    index index.html index.htm;
    location / {
        autoindex on;
        autoindex_localtime  on;
        autoindex_exact_size on;
    }
}

#server {
#    listen 82;
#    charset utf-8;
#    location / {
#        proxy_connect_timeout 60;
#        proxy_read_timeout 600s;
#        proxy_send_timeout 600s;
#        proxy_pass http://LocalHostIP:12200;
#        # WS
#        proxy_http_version 1.1;
#        proxy_set_header Connection "upgrade";
#        proxy_set_header Upgrade $http_upgrade;
#        # 其他
#        proxy_set_header Host            $host;
#        proxy_set_header X-Real-IP       $remote_addr;
#        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#    }
#}
