
# upstream My12210 { server 127.0.0.1:12210; } server { listen 12210; proxy_pass My12210; proxy_timeout 300s; proxy_connect_timeout 60s; tcp_nodelay on; }
# upstream My12220 { server 127.0.0.1:12220; } server { listen 12220; proxy_pass My12220; proxy_timeout 300s; proxy_connect_timeout 60s; tcp_nodelay on; }
# upstream My12230 { server 127.0.0.1:12230; } server { listen 12230; proxy_pass My12230; proxy_timeout 300s; proxy_connect_timeout 60s; tcp_nodelay on; }
# upstream My12240 { server 127.0.0.1:12240; } server { listen 12240; proxy_pass My12240; proxy_timeout 300s; proxy_connect_timeout 60s; tcp_nodelay on; }
